### ISSUE TITLE
como puedo que ande el plugin 

### ISSUE THREAD

**Issue by Alias2007** [NetherGamesMC/ProxyTransport-PM#124]
Bueno seriaa que no registra el raklib

![image](https://github.com/NetherGamesMC/ProxyTransport-PM/assets/109934470/bf67bc92-e054-426d-91e9-a5fcf9d4d57d)

**Comment by dries-c** [comment]
it seems like you've already disabled the raklib interface

**Comment by Alias2007** [comment]
> it seems like you've already disabled the raklib interface



> it seems like you've already disabled the raklib interface

pero no se puede arreglar lo de eso
