### ISSUE TITLE
Connection reset when try to join

### ISSUE THREAD

**Issue by xerenahmed** [NetherGamesMC/ProxyTransport-PM#30]
Thank you all who made an open-source project like this. I wanted to try but sadly I couldn't use it.

`Proxy failed to start: socket_set_option(): Unable to set socket option [55]: No buffer space available`
After some reproduction, I saw `socket_set_option` buffer size sets `8 * 1024 * 1024` and I changed 8 to 6.

There is no method for `RakLibInterface::getBroadcaster($this->server, ProtocolInfo::CURRENT_PROTOCOL)`
and I replicated it with:
```php
new StandardPacketBroadcaster($this->server)
```

Now it's working! Expect one thing: when I try to join something happening.
```
// WDPE
20:39:39 [ERROR] Pipeline threw exception for player xerenahmed
java.net.SocketException: Connection reset
....

// PM
17:39:39.264 ProxyThread DEBUG > Socket(0) created a session from 127.0.0.1:54183
17:39:39.377 Server INFO > [NetworkSession: 127.0.0.1 54183] Session opened
17:39:39.533 Server DEBUG > [NetworkSession: 127.0.0.1 54183] SetActorMotionPacket: KA==
17:39:39.534 Server INFO > [NetworkSession: 127.0.0.1 54183] Session closed due to Socket disconnect
17:39:39.534 ProxyThread DEBUG > Disconnected socket with id 0
```

**Comment by larryTheCoder** [comment]
Currently, ProxyTransport-PM only support our forked version of PocketMine-MP, it is not going to work with the original PocketMine-MP which is not ideal to say.
