### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by MaskioSss** [NetherGamesMC/ProxyTransport-PM#59]
1976)
  #3 pmsrc/src/Server(1042): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#21946)
  #4 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#5, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
  #5 pmsrc/src/PocketMine(362): pocketmine\server()
  #6 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by dries-c** [comment]
The entire crash dump is missing.

**Comment by MaskioSss** [comment]
How do you explain it to me a little better because what you said doesn't seem to have anything to do

**Comment by MaskioSss** [comment]
[19:14:13.815] [Server thread/CRITICAL]: Error: "Class "libproxy\ProxyNetworkInterface" not found" (EXCEPTION) in "plugins/ProxyTransport-PM/src/NetherGames/ProxyTransport/ProxyTransport" at line 42
--- Stack trace ---
