### ISSUE TITLE
can't join

### ISSUE THREAD

**Issue by xxFLORII** [NetherGamesMC/ProxyTransport-PM#6]
when i try to join with this i stuck in the "Locating Server" screen.

I only get this in the log: https://paste.ee/p/NTyZB

**Comment by xxFLORII** [comment]
`ProxyServer.getInstance().registerServerInfo(new CustomTransportServerInfo(
                            "" + ((RegisterServerPacket) packet).name,
                            new InetSocketAddress("127.0.0.1", Integer.parseInt("" + ((RegisterServerPacket) packet).port)),
                            null
                    ));`

Here I add the servers

**Comment by Driesboy** [comment]
Could you give us more information about which version of WD you're running, which commit of the ProxyTransport plugin for WD you're using etc etc?

**Comment by xxFLORII** [comment]
Waterdog version: 1.1.8 ( 57c5872c1d067fd7a6b4049d318900c067b53dce )
ProxyTransport version: 1.1
ProxyTransport-PM & libProxy: latest downloadable version

**Comment by dries-c** [comment]
Should work now
