### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by UnknownNull** [NetherGamesMC/ProxyTransport-PM#7]
2022-08-11 [02:13:47.718] [Server thread/CRITICAL]: Error: "Class "libproxy\ProxyNetworkInterface" not found" (EXCEPTION) in "plugins/ProxyTransport-PM-master/src/NetherGames/ProxyTransport/ProxyTransport" at line 42
--- Stack trace ---
  #0 pmsrc/src/plugin/PluginBase(117): NetherGames\ProxyTransport\ProxyTransport->onEnable()
  #1 pmsrc/src/plugin/PluginManager(448): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #2 pmsrc/src/Server(1419): pocketmine\plugin\PluginManager->enablePlugin(object NetherGames\ProxyTransport\ProxyTransport#25733)
  #3 pmsrc/src/Server(1024): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#25732)
  #4 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#4, string[39] C:\Users\Administrator\Documents\1.hub\, string[47] C:\Users\Administrator\Documents\1.hub\plugins\)
  #5 pmsrc/src/PocketMine(327): pocketmine\server()
  #6 pmsrc(11): require(string[83] phar://C:/Users/Administrator/Documents/1.hub/PocketMine-MP.phar/src/PocketMine.)
--- End of exception information ---
2022-08-11 [02:13:47.718] [Server thread/INFO]: Stopping other threads

pocketmine api4

**Comment by Driesboy** [comment]
seems like you didn't install the composer dependencies correctly

**Comment by UnknownNull** [comment]
Except what are its dependencies?

**Comment by UnknownNull** [comment]
but installed dependencies...

**Comment by Driesboy** [comment]
Could you check if there's a vendor folder in your plugin, since you're running it from source

**Comment by UnknownNull** [comment]
Where should I add libproxy?

**Comment by larryTheCoder** [comment]
In your project root folder (ProxyTransport-PM-master), you must run
```
composer install
```

Composer is required to build and run this project with its dependencies. You will be able to run this plugin normally after that step.

**Comment by UnknownNull** [comment]
> 



> In your project root folder (ProxyTransport-PM-master), you must run
> 
> ```
> composer install
> ```
> 
> Composer is required to build and run this project with its dependencies. You will be able to run this plugin normally after that step.

this error in terminal : 'php' is not recognized as an internal or external command,
operable program or batch file.

**Comment by UnknownNull** [comment]
oh 
The composer is not installed

**Comment by UnknownNull** [comment]
![image](https://user-images.githubusercontent.com/91208232/193071827-24f5ca85-662e-4780-aa75-36fbdaaf3400.png)

**Comment by dries-c** [comment]
This means you don't have PHP as executable

**Comment by dries-c** [comment]
This has nothing to do with our code, your CLADevs\VanillaX\session\Session class doesn't extend NetworkSession
